# Generated by Django 4.0.7 on 2024-02-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_group_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='type',
            field=models.CharField(choices=[('1', 'staff'), ('2', 'customer'), ('3', 'supervisor')], default='1', max_length=50),
        ),
    ]
