# Generated by Django 4.0.7 on 2024-02-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_baseuser_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
