# Generated by Django 4.0.7 on 2024-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_baseuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='users.basegroup', verbose_name='groups'),
        ),
    ]
