# Generated by Django 4.0.7 on 2024-02-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0011_alter_baseuser_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basegroup',
            options={},
        ),
        migrations.RemoveField(
            model_name='basegroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='basegroup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='basegroup',
            name='permissions',
        ),
        migrations.AddField(
            model_name='basegroup',
            name='group_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
