# Generated by Django 4.0.7 on 2024-02-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_basegroup_options_remove_basegroup_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseGroup',
        ),
    ]
