# Generated by Django 4.0.7 on 2024-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0013_delete_basegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
