# Generated by Django 4.0.7 on 2024-02-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_company_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='group',
        ),
    ]
