# Generated by Django 4.0.7 on 2024-02-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_add_new_product', 'can add new product'), ('dg_view_product', 'OBP can view product')]},
        ),
    ]
